# Generated by Django 5.0.4 on 2024-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerremasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Bod', 'Bodegero (Interno)'), ('Con', 'Contador (Interno)'), ('Ven', 'Vendedor (Interno)'), ('Cli', 'Cliente (Externo)')], default='Cli', max_length=20),
        ),
    ]
