# Generated by Django 4.2.6 on 2024-05-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_categoria_categoriaproducto_cliente_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.producto'),
        ),
    ]
