# Generated by Django 4.2.2 on 2024-05-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_categoriaproducto_cliente_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
    ]
