# Generated by Django 4.2.2 on 2024-05-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_detallescompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tipocontacto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
