# Generated by Django 4.2.2 on 2024-05-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
