# Generated by Django 4.2.2 on 2024-05-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
    ]
