# Generated by Django 5.0.4 on 2024-05-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_detallescompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='responsabilidadtienda',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.RemoveField(
            model_name='responsabilidadtienda',
            name='tienda',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='ResponsabilidadTienda',
        ),
    ]
