# Generated by Django 5.0.6 on 2024-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_postal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Bod', 'Bodegero (Interno)'), ('Con', 'Contador (Interno)'), ('Ven', 'Vendedor (Interno)'), ('Cli', 'Cliente (Externo)'), ('Adm', 'Admin (Interno)'), ('Des', 'Desarrollador')], default='Cli', max_length=20),
        ),
    ]
