# Generated by Django 4.2.2 on 2024-06-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user_pais_abreviado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactos',
        ),
    ]
